"""agregando una tabla de password

Revision ID: 8092b9d591c1
Revises: d0dd694bc0cc
Create Date: 2023-05-18 20:00:03.278548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8092b9d591c1'
down_revision = 'd0dd694bc0cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
